### ISSUE TITLE
Applied conventions on 7 repositories

### ISSUE THREAD

**Issue by madebr** [madebr/conan-repo-actions-community#2]
Hello,

`bincrafters-conventions` and `conan-readme-generator` were executed on the following repositories:

- [ ] conan-libvpx: testing/1.8.0 madebr/conan-repo-actions-conan-libvpx#1
- [ ] conan-libx264: testing/20190605 madebr/conan-repo-actions-conan-libx264#1
- [ ] conan-libx265: testing/3.0 madebr/conan-repo-actions-conan-libx265#1
- [ ] conan-ogg: testing/1.3.3 madebr/conan-repo-actions-conan-ogg#1
- [ ] conan-openh264: testing/1.7.0 madebr/conan-repo-actions-conan-openh264#1
- [ ] conan-opus: testing/1.3.1 madebr/conan-repo-actions-conan-opus#1
- [ ] conan-vorbis: testing/1.3.6 madebr/conan-repo-actions-conan-vorbis#1
