### ISSUE TITLE
Applied conventions on 9 repositories

### ISSUE THREAD

**Issue by madebr** [madebr/conan-repo-actions-community#3]
Hello,

`bincrafters-conventions` and `conan-readme-generator` were executed on the following repositories:

- [ ] conan-libfdk_aac: testing/2.0.0 madebr/conan-repo-actions-conan-libfdk_aac#1
- [ ] conan-libmp3lame: testing/3.100 madebr/conan-repo-actions-conan-libmp3lame#1
- [ ] conan-libvpx: testing/1.8.0 madebr/conan-repo-actions-conan-libvpx#2
- [ ] conan-libx264: testing/20190605 madebr/conan-repo-actions-conan-libx264#2
- [ ] conan-libx265: testing/3.0 madebr/conan-repo-actions-conan-libx265#2
- [ ] conan-ogg: testing/1.3.3 madebr/conan-repo-actions-conan-ogg#2
- [ ] conan-openh264: testing/1.7.0 madebr/conan-repo-actions-conan-openh264#2
- [ ] conan-opus: testing/1.3.1 madebr/conan-repo-actions-conan-opus#2
- [ ] conan-vorbis: testing/1.3.6 madebr/conan-repo-actions-conan-vorbis#2
