### ISSUE TITLE
Applied conventions on 8 repositories

### ISSUE THREAD

**Issue by madebr** [madebr/conan-repo-actions-community#5]
Hello,

 and `conan-readme-generator` was executed on the following repositories:

- [ ] conan-libffi: testing/3.2.1 madebr/conan-repo-actions-conan-libffi#1
- [ ] conan-mpdecimal: testing/2.4.2 madebr/conan-repo-actions-conan-mpdecimal#1
- [ ] conan-lzma: testing/5.2.4 madebr/conan-repo-actions-conan-lzma#3
- [ ] conan-libiconv: testing/1.15 madebr/conan-repo-actions-conan-libiconv#3
- [ ] conan-libtirpc: testing/1.1.4 madebr/conan-repo-actions-conan-libtirpc#1
- [ ] conan-libnsl: testing/1.2.0 madebr/conan-libnsl-1#1
- [ ] conan-sqlite3: testing/3.28.0 madebr/conan-repo-actions-conan-sqlite3#1
- [ ] conan-libuuid: testing/1.0.3 madebr/conan-repo-actions-conan-libuuid#1

Dependencies of cpython
