### ISSUE TITLE
Applied conventions on 5 repositories

### ISSUE THREAD

**Issue by madebr** [madebr/conan-repo-actions-community#6]
Hello,

`bincrafters-conventions` was executed on the following repositories:

- [ ] conan-libffi: testing/3.2.1 madebr/conan-repo-actions-conan-libffi#2
- [ ] conan-mpdecimal: testing/2.4.2 madebr/conan-repo-actions-conan-mpdecimal#2
- [ ] conan-libtirpc: testing/1.1.4 madebr/conan-repo-actions-conan-libtirpc#2
- [ ] conan-libnsl: testing/1.2.0 madebr/conan-libnsl-1#2
- [ ] conan-sqlite3: testing/3.28.0 madebr/conan-repo-actions-conan-sqlite3#2

Dependencies of cpython
